# Generated by Django 4.2 on 2023-07-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
